from typing import Protocol


class AuthTokenIssuer(Protocol):
    def create_access_token(self, user_id: str) -> str: ...

    def create_refresh_token(self, user_id: str) -> str: ...

    def decode_refresh_token(self, token: str) -> str: ...

    def decode_access_token(self, token: str) -> str: ...
